[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

# ここからcolorschemeを取ってきているぽいけどなくても大丈夫そう
# [[plugins]]
# repo = 'overcache/NeoSolarized'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = """
source ~/.config/nvim/plugins/denite.rc.vim
"""

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'jlanzarotta/bufexplorer'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
# Yet Another Remote Plugin Framework for Neovim
repo = 'roxma/nvim-yarp'
if = '''!has('nvim')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim')'''

[[plugins]]
repo = 'neovim/python-client'
if = '''!has('nvim')'''

[[plugins]]
repo = "neoclide/coc.nvim"
merged = 0
rev = "release"
hook_add = """
source ~/.config/nvim/plugins/coc.rc.vim
"""

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'preservim/nerdcommenter'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'yucchini/vim-zenspace'

# 入れてみたいがまだ内容把握してないので保留
# [[plugins]]
# repo = 'dense-analysis/ale'

# # emmet for vim
# [[plugins]]
# repo = 'mattn/emmet-vim'
