##################
# Plugin Manager
##################
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

##################
# Git / GitHub
##################
[[plugins]]
repo = 'uki1014/vim-to-github'
hook_add = """
lua vim.g.to_github_clipboard = '1'
lua vim.api.nvim_set_keymap('n', '<Leader>gj', ':ToGithubBlobDevelopBranch<CR>', { noremap = true })
lua vim.api.nvim_set_keymap('n', '<Leader>gb', ':ToGithubBlameDevelopBranch<CR>', { noremap = true })
lua vim.api.nvim_set_keymap('n', '<Leader>G', ':ToGithubBlobCommitHash<CR>', { noremap = true })
lua vim.api.nvim_set_keymap('n', '<Leader>GB', ':ToGithubBlameCommitHash<CR>', { noremap = true })
lua vim.api.nvim_set_keymap('n', '<Leader>g', ':ToGithubTargetPullRequest<CR>', { noremap = true })
lua vim.api.nvim_set_keymap('n', '<Leader>j', ':ToGithubTargetPullRequestFromCommitHash<CR>', { noremap = true })
"""

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = """
source ~/.config/nvim/lua/plugins/lightline.lua
"""

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = ['plenary.nvim']
hook_add = """
lua require('gitsigns').setup()
lua vim.api.nvim_set_keymap('n', '<Leader>gl', ':lua require"gitsigns".blame_line({ full = true })<CR>', { noremap = true })
"""

##################
# Filer
##################
[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'uki1014/defx.nvim'
depends = ['defx-git']
hook_add = """
source ~/.config/nvim/lua/plugins/defx.lua
"""

##################
# Fuzzy Finder
##################
[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = """
source ~/.config/nvim/lua/plugins/telescope.lua
"""

[[plugins]]
repo = "neoclide/coc.nvim"
merged = 0
rev = "v0.0.81"
hook_add = """
source ~/.config/nvim/lua/plugins/coc.lua
"""

##################
# Utils
##################
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = """
lua vim.g.closetag_filenames = '*.html,*.xhtml,*xml,*.phtml,*.erb,*.php,*.vue,*.js,*.jsx,*.ts,*.tsx'
"""

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = """
lua vim.g.indentLine_fileTypeExclude = {'help', 'nerdtree', 'calendar', 'thumbnail', 'tweetvim', 'defx'}
lua vim.g.indentLine_color_term = '239'
lua vim.g.indentLine_color_gui = '#708090'
lua vim.g.indentLine_char_list = {'┊', '┊', '┊', '┊'}
"""

[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = """
" デフォルトのキーマッピングをオフ
lua vim.g.NERDCreateDefaultMappings = '0'
" コメントアウト時にスペースを1つ挿入
lua vim.g.NERDSpaceDelims = '1'
" コメント記号を左に揃える
lua vim.g.NERDDefaultAlign = 'left'
" fishのコメントアウトが対応していなかったので追加
lua vim.g.NERDCustomDelimiters = { fish = { left = '#' } }

" コメントアウト
lua vim.api.nvim_set_keymap('n', '<Leader>f', '<Plug>NERDCommenterToggle', {})
lua vim.api.nvim_set_keymap('v', '<Leader>f', '<Plug>NERDCommenterToggle', {})
" コメントアウトしてインサートモード
lua vim.api.nvim_set_keymap('n', '<Leader>r', '<Plug>NERDCommenterAppend', {})
" ブロックコメントアウト
lua vim.api.nvim_set_keymap('n', '<Leader>bf', '<Plug>NERDCommenterSexy', {})
lua vim.api.nvim_set_keymap('v', '<Leader>bf', '<Plug>NERDCommenterSexy', {})
"""

[[plugins]]
repo = 'uki1014/vim-zenspace'
hook_add = """
lua vim.g['zenspace#default_mode'] = 'on'
"""

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'previm/previm'
hook_add = """
lua vim.g.previm_open_cmd = 'open -a "Google Chrome"'
lua vim.api.nvim_set_keymap('n', '<Leader>a', ':PrevimOpen<CR>', { noremap = true })
"""

[[plugins]]
repo = 'thaerkh/vim-workspace'
hook_add = """
lua vim.g.workspace_autocreate = '1'
lua vim.g.workspace_undodir = os.getenv('HOME')..'/.config/nvim/sessions/'
lua vim.g.workspace_autosave = '0'
lua vim.g.workspace_session_directory = os.getenv('HOME')..'/.config/nvim/sessions/'
"""

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = """
lua vim.g.better_whitespace_guicolor = 'darkred'
lua vim.g.strip_whitespace_on_save = 0
lua vim.api.nvim_set_keymap('n', '<Leader>y', ':StripWhitespace<CR>', { noremap = true })
"""

[[plugins]]
repo = 'numToStr/BufOnly.nvim'
hook_add = """
lua vim.api.nvim_set_keymap('n', '<Leader>ba', ':BufOnly<CR>', { noremap = true })
"""

[[plugins]]
repo = 'windwp/nvim-spectre'
hook_add = """
source ~/.config/nvim/lua/plugins/nvim-spectre.lua
"""

[[plugins]]
repo = 'mtdl9/vim-log-highlighting'

# [[plugins]]
# repo = 'jamestthompson3/nvim-remote-containers'
