[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git']
hook_add = """
source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = """
source ~/.config/nvim/plugins/denite.rc.vim
"""

[[plugins]]
# Yet Another Remote Plugin Framework for Neovim
repo = 'roxma/nvim-yarp'
if = '''!has('nvim')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim')'''

[[plugins]]
repo = 'neovim/python-client'
if = '''!has('nvim')'''

[[plugins]]
repo = "neoclide/coc.nvim"
merged = 0
rev = "release"
hook_add = """
source ~/.config/nvim/plugins/coc.rc.vim
"""

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'preservim/nerdcommenter'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'uki1014/vim-zenspace'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'chrisbra/Colorizer'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'previm/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/open-browser-github.vim'

# [[plugins]]
# repo = 'nvim-treesitter/nvim-treesitter'

# [[plugins]]
# repo = 'dense-analysis/ale'

# [[plugins]]
# repo = 'mattn/emmet-vim'
