name: Setup my dotfiles for macOS

on:
  push:
    paths:
      - 'scripts/**'
      - 'shell/**'
    paths-ignore:
      - 'shell/alias.sh'
      - '**.md'
      - '*ignore'

jobs:
  installer-test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Execute dotfiles installer.sh
        run: bash <(curl -s https://raw.githubusercontent.com/uki1014/dotfiles/master/scripts/install.sh)
