name: Setup dotfiles for macOS

on:
  push:
    paths:
      - '.github/**'
      - 'scripts/**'
      - 'shell/**'
      - '!shell/alias.sh'
      - '!**.md'
      - '!*ignore'

jobs:
  installer-for-macOS:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Execute dotfiles installer.sh
        run: bash <(curl -s https://raw.githubusercontent.com/uki1014/dotfiles/master/scripts/install.sh)
